# Generated by Django 5.1.5 on 2025-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='codeID',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
