# Generated by Django 5.1.5 on 2025-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_codeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userID', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('Role', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
